### ISSUE TITLE
index.js:2177 20:03:35:66 ERROR: Get server node failed [invalid key] 

### ISSUE THREAD

**Issue by oliveirawesley** [AgoraIO-Community/OpenAgoraWeb-React#7]
Hi Guys,

I updated AGORA_API_ID, with my Customer ID. But i do not find where i can update the customer certificate and i received this error when i entered on the video room:
20:10:01:597 ERROR: Get server node failed [invalid key] http://webcs-2.agora.io:5669/getwebgw/jsonp

Someone can help me?

**Comment by plutoless** [comment]
closed for inactivity
